### ISSUE TITLE
table

### ISSUE THREAD

**Issue by Huang-Yujiong** [browneyedsoul/RemNote-CSS-Library#2]
your work is awsome  about table1 and table2
can we use table in remnote 1.4 ? there is not a great CSS like yours  these days , before remnote update last two month  ,  so sad

**Comment by browneyedsoul** [comment]
Hi, @Huang-Yujiong 
Sorry to hear that.
but Martin said [in this video](https://youtu.be/O2NkVWR-9t0?t=877)
he already would have broken ground to make tables so we better have to watch him.
For technical reasons, CSS tables do not work anymore unless remnote changes its structure or CSS organization makes other rules.

**Comment by browneyedsoul** [comment]
I saw a message from hannesfrank about tag-related gimmicks from the discord channel, he already requested an updated version and just waiting for martin to pull the request so we will use it like before. please wait for the next remnote update!

**Comment by Huang-Yujiong** [comment]
thank you verymuch
