### ISSUE TITLE
Making a Github Pages for this repository

### ISSUE THREAD

**Issue by weavermarquez** [browneyedsoul/RemNote-CSS-Library#3]
안녕하세요!

I saw your overhaul to your README and am very excited for the increase in usability!

I'm curious if you are planning to create a github pages for your repository. This will enable other users to automatically have the most up to date version of your CSS and increase adoption.

Unfortunately, linking directly to the raw file on your repository does not work, so it must be through Github Pages. As we see from eustachi0 [here,](https://github.com/eustachi0/RemNoteThemes/blob/main/RemNoteDarkTheme-by-eustachio.md), users simply use `@import url("https://eustachi0.github.io/RemNoteThemes/CSS/01_Body.css");` in their Custom CSS Rem, instead of copy-pasting the entire CSS text.

I forked your repo to combine it with my other snippets. Without CS experience, it'd be impossible.

If you are wary about using github pages, I wonder if we could instead make a .md file that users can copy-paste instead, formatted for remnote. Or possibly a fork of Hannes' library.

**Comment by browneyedsoul** [comment]
I really appreciate your kind feedback!

You already know that I'm a noob to programming😄, and still in a learning process. So it can be a little bit awkward in some situations like you mentioned (not friendly to user deployment, etc.)

I will definitely focus on the way of deployment through the github pages method. Not just git experience, but This is also a great learning material for me. It wouldn't be taking a long time

For me, eustachi0's repository is a very good example of my study. He is a real professionalist even though he made his work just for fun.

And again, I'm very pleased that you are using my library and made me a great suggestion!

**Comment by browneyedsoul** [comment]
Hi, @weavermarquez I've done this work! please check 😄

**Comment by weavermarquez** [comment]
Awesome! ^^

You're certainly much more experienced with CSS than I am, that's for sure! I love your snippets. Your vision for is quite a wide scope, making snippets and enabling dark mode compatability! I strongly appreciate your contributions and am excited to learn from you as well.

It's difficult to reconcile how broad the demands are in making a thing vs distributing it, so it's definitely not an issue, and I'd be happy to help. I hope others may be interested in helping.

Would you appreciate suggestions/pull requests from me in the future re: import ease and usability? I want to get back into programming since it's been a while and it'd help restore my sanity.

I'm tempted to do a deep dive into the code and see what we could do to make it easily adjustable for others and maybe even make it so that there's a style standardization? Though, I don't really know how much work that would take - I'm not experienced with UI development beyond a few courses where I made apps (which were not good!)

**Comment by weavermarquez** [comment]
Also, I wonder if this could help you get a job with Remnote, haha! I'm not looking for a job myself, but maybe it could be possible - your usability snippets are certainly the best I've seen in this community!  

https://www.remnote.com/careers
:eyes:
> Open Positions
> Frontend Engineer
> Frontend Engineer Intern
> Operations and Growth
> Q&A Engineer
> Talent Sourcer
> UI Designer

**Comment by browneyedsoul** [comment]
Absolutely! I always appreciate your kind feedback, suggestion, request whatever in the future, haha
and I really love RemNote and someday I will apply for the team. I hope so. 
If I have some chances I definitely will apply for the team.
However I'm doubting my current skills and tech stack, so I think I need to learn more about WEB skills to meet their needs.
Anyway, Thank you for suggesting that to me. :smile:

Merry Christmas @weavermarquez ! 🎄
