### ISSUE TITLE
Rem Tree.CSS seems to have some problems

### ISSUE THREAD

**Issue by kyle-one** [browneyedsoul/RemNote-CSS-Library#5]
![image](https://user-images.githubusercontent.com/44631434/178704300-852bd4f6-11b2-41a2-8184-aaeeab747d73.png)

It cannot be centered, and the close icon of tag is not hidden.

**Comment by browneyedsoul** [comment]
Hey, @kyle-one Thanks for the report!
To be honest I've been using this with 'no bullet editor mode' so I couldn't realize what was wrong.
Check the latest update pls!

**Comment by kyle-one** [comment]
Is it a browser compatibility problem? I use the latest version of chrome. (103.0.5060.114)

**Comment by browneyedsoul** [comment]
![220713-201452](https://user-images.githubusercontent.com/56161102/178721378-298aafb7-5813-4f40-b5e8-dc6ca80f80b4.png)
↑ This is tested in my TEST KB

It seems that it also has some conflict with your rem-bullet position pls check other snip which can affect bullet position

And you want the X button not to seen in your tree, how about going to use UI declutter series - Hide Specific tag? 

Thanks
