### ISSUE TITLE
When I use rem tree.CSS and enter thr rem where the "tree" tag is located, the reference becomes very strange

### ISSUE THREAD

**Issue by kyle-one** [browneyedsoul/RemNote-CSS-Library#8]
![image](https://user-images.githubusercontent.com/44631434/179693454-edf396d2-239c-41b8-96fd-74925839dafd.png)

![image](https://user-images.githubusercontent.com/44631434/179693518-ce32e8db-a0c8-4c7f-b399-90259951c3e4.png)

**Comment by browneyedsoul** [comment]
How about this one?
![220719-180130](https://user-images.githubusercontent.com/56161102/179711638-42512499-ca0e-486b-8543-d8a74488a2cd.png)
